name: Deploy Angular + .NET 8 App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
   
    - name: Install Angular dependencies
      run: |
        cd UKParliament.CodeTest.Web/ClientApp
        npm install

    - name: Build Angular app
      run: |
        cd UKParliament.CodeTest.Web/ClientApp
        npm run build -- --output-path=../wwwroot --configuration production

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET app
      run: dotnet publish ./UKParliament.CodeTest.Web/UKParliament.CodeTest.Web.csproj -c Release -o ./publish

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: uk-fernando-magrina-interview
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish
