name: Deploy .NET App to Azure App Service

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish
        run: |
          dotnet publish -c Release -o ./publish

      - name: Deploy via ZIP using publish profile
        uses: azure/webapps-deploy@v2
        with:
          app-name: uk-fernando-magrina-interview
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_USERNAME }}:${{ secrets.AZURE_WEBAPP_PASSWORD }}
          package: ./publish
